name: pdist_aggregation
channels:
  - conda-forge
dependencies:
  - python=3.9
  - compilers
  - jupyter
  - numpy
  - cython
  - matplotlib
  - seaborn
  - pandas
  - scikit-learn-intelex
  - pyaml
  - pip
  - theadpoolctl
  - pre-commit
  - pip:
      - --pre
      - --index-url https://pypi.anaconda.org/scipy-wheels-nightly/simple
      - scikit-learn
      # Install pdist_agregation from source
      - -e ./src
      # Install cython 3 from upstream directly
      - -e git+https://github.com/cython/cython.git#egg=cython
