estimators:
  - name: "Double chunking"
    estimator: nn.NearestNeighbors
    chunk: True

datasets:
  # X_train taller
  - n_samples_train: 1e6
    n_samples_test: 1e3
    n_features: 50
  - n_samples_train: 1e6
    n_samples_test: 1e3
    n_features: 1e2
  # X_test taller
  - n_samples_train: 1e3
    n_samples_test: 1e6
    n_features: 50
  - n_samples_train: 1e3
    n_samples_test: 1e6
    n_features: 1e2

chunk_size: # [2 ** i for i in range(9, 13)]
  - 128
  - 256
  - 512
  - 1024
  - 2048
  - 4096

n_neighbors:
  - 1
  - 10
  - 100
  - 1000
