estimators:
  - name: sklearn
    estimator: sklearn.neighbors.NearestNeighbors
    chunk: False
  - name: daal4py
    estimator: daal4py.sklearn.neighbors.NearestNeighbors
    chunk: False
  - name: "Double chunking @ fdc9d31"
    estimator: nn.NearestNeighborsDoubleChunking
    chunk: True

datasets:
  # X_train taller
  - n_samples_train: 1e6
    n_samples_test: 1e3
    n_features: 50
  - n_samples_train: 1e6
    n_samples_test: 1e3
    n_features: 1e2
  - n_samples_train: 1e3
    n_samples_test: 1e1
    n_features: 500

  # X_test taller
  - n_samples_train: 1e3
    n_samples_test: 1e6
    n_features: 50
  - n_samples_train: 1e3
    n_samples_test: 1e6
    n_features: 1e2

working_memories:
  - 32768
  - 65536
  - 131072
  - 262144
  - 524288
  - 1048576
  - 2097152
  - 4194304
  - 8388608
  - 16777216

n_neighbors:
  - 10
