estimators:
  - name: sklearn
    estimator: sklearn.neighbors.NearestNeighbors
    chunk: False
  - name: daal4py
    estimator: daal4py.sklearn.neighbors.NearestNeighbors
    chunk: False
  - name: "Parallel on X_train"
    estimator: nn.NearestNeighborsParrallelXtrain
    chunk: True
  - name: "Parallel on X_test"
    estimator: nn.NearestNeighborsParrallelXtest
    chunk: True

n_trials: 5

datasets:
  # X_train taller
  - n_samples_train: 1e5
    n_samples_test: 1e3
    n_features: 50
  - n_samples_train: 1e5
    n_samples_test: 1e3
    n_features: 1e2
  - n_samples_train: 1e5
    n_samples_test: 1e3
    n_features: 500
  # X_test taller
  - n_samples_train: 1e3
    n_samples_test: 1e5
    n_features: 50
  - n_samples_train: 1e3
    n_samples_test: 1e5
    n_features: 1e2
  - n_samples_train: 1e3
    n_samples_test: 1e5
    n_features: 500

chunk_size: # [2 ** i for i in range(9, 13)]
  - 128
  - 256
  - 512
  - 1024
  - 2048
  - 4096

n_neighbors:
  - 1
  - 10
  - 100
